# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'QRCodeGenerator' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for QRCodeGenerator
    pod 'SnapKit', '~> 0.22.0'
end
